### PR TITLE
SMS-6

### PR DESCRIPTION
**Pull request by namontaGaines**

### CODE REVIEW

**Comment by namontaGaines** [comment]
RFI

**Review by chrisnellis — DISMISSED** [review]
UI inconsistent

**Comment by namontaGaines** [comment]
RFI

**Comment by ghost** [comment]
Notification sent!

**Comment by namontaGaines** [comment]
RFI

**Comment by ghost** [comment]
Notification sent!

**Review by chrisnellis — COMMENTED** [review]
Make sure to remove highlighting of the arrow on the table

**Comment by namontaGaines** [comment]
RFI

**Comment by ghost** [comment]
Notification sent!

**Review by chrisnellis — APPROVED** [review]

**Pull request merged**
