### PR TITLE
Sms 68 v2

### PR DESCRIPTION
**Pull request by jake-basten**

### CODE REVIEW

**Comment by jake-basten** [comment]
RFI

**Comment by ghost** [comment]
Notification sent!

**Review by chrisnellis — DISMISSED** [review]

**Comment by jake-basten** [comment]
RFI

**Comment by ghost** [comment]
Notification sent!

**Comment by chrisnellis** [comment]
RFI

**Comment by ghost** [comment]
Notification sent!

**Review by chrisnellis — APPROVED** [review]

**Pull request merged**
