### PR TITLE
Sms 68

### PR DESCRIPTION
**Pull request by jake-basten**
Added html and controller files.  Created button to go to new page for scheduling certifications.

### CODE REVIEW

**Comment by chrisnellis** [comment]
RFI

**Comment by ghost** [comment]
Notification sent!

**Comment by chrisnellis** [comment]
RFI

**Comment by chrisnellis** [comment]
RFI

**Comment by ghost** [comment]
Notification sent!

**Comment by jake-basten** [comment]
RFI

**Comment by ghost** [comment]
Notification sent!

**Review by chrisnellis — CHANGES_REQUESTED** [review]
Wait for feature branch tests to pass first!!!

**Comment by jake-basten** [comment]
RFI

**Comment by ghost** [comment]
Notification sent!

**Review by chrisnellis — DISMISSED** [review]

**Review by chrisnellis — CHANGES_REQUESTED** [review]
Don't just comment out the logs and alerts, remove them

**Comment by jake-basten** [comment]
RFI

**Comment by ghost** [comment]
Notification sent!

**Review by chrisnellis — APPROVED** [review]

**Pull request merged**
